version: '3.8'
services:
  nginx: 
    image: nginx
    ports:
      - "8083:80"
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/site.conf:/etc/conf.d/default.conf
      - newfront:/usr/share/nginx/html/newfront
      - oldfront:/usr/share/nginx/html/oldfront
  newfront:
    build:
      context: total-service-frontend-client
      dockerfile: Dockerfile
    volumes:
      - newfront:/app/dist
  oldfront:
    build:
      context: total-service-front
      dockerfile: Dockerfile
    volumes:
      - oldfront:/app/build
volumes:
  newfront:
  oldfront: